apiVersion: v1
kind: Secret
metadata:
  name: dingo-ssh-key
type: Opaque
data:
  # Base64 encoded SSH private key
  # echo -n "$(cat /path/to/ssh/key)" | base64
  id_rsa: <base64-encoded-ssh-key-here>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dingo-config
data:
  target-ip: "147.185.41.233"
  target-port: "20046"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dingo
  template:
    metadata:
      labels:
        app: dingo
    spec:
      containers:
      - name: dingo
        image: dingo-ssh:latest
        args:
        - "$(TARGET_IP)"
        - "$(TARGET_PORT)"
        env:
        - name: TARGET_IP
          valueFrom:
            configMapKeyRef:
              name: dingo-config
              key: target-ip
        - name: TARGET_PORT
          valueFrom:
            configMapKeyRef:
              name: dingo-config
              key: target-port
        volumeMounts:
        - name: ssh-key
          mountPath: /app/.ssh
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: dingo-ssh-key
          defaultMode: 0400
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dingo-job
spec:
  template:
    spec:
      containers:
      - name: dingo
        image: dingo-ssh:latest
        args:
        - "147.185.41.233"
        - "20046"
        volumeMounts:
        - name: ssh-key
          mountPath: /app/.ssh
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: dingo-ssh-key
          defaultMode: 0400
      restartPolicy: Never
  backoffLimit: 3 